<a href="https://colab.research.google.com/github/Rijinputhiyonnan/ICT-daily-task-Rijin/blob/main/Daily_task_05_07_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#1
4def number_comparison(x,y,z):
  nmax=max(x,y,z)

  return(nmax)
p=int(input("first number- "))
q=int(input("second number- "))
r=int(input("Third number- "))

print(number_comparison(p,q,r))

first number- 99
second number- 43
Third number- 45
99


In [4]:
#2
def area(r):
  a=22/7*r*r
  return(a)



In [6]:
x=float(input("enter the value of r- "))
print(area(x))

enter the value of r- 7
154.0


In [1]:
#3

def prime_or_not(n):
  if n>1:
    for i in range(2,n):
      if n%i==0:


        return(False)
        break
    else:
        return(True)

  else:
    print("entered value is neither prime nor composite, or invalid entry")

In [4]:
c=int(input("enter the number-  "))
print(prime_or_not(c))

enter the number-  5
True


In [7]:
from pickle import TRUE
#4
def palindrome(s):
  p=s[::-1]
  if s==p:
    return(True)
  else:
    return(False)

In [8]:
m=input("enter a string- ")
palindrome(m)

enter a string- tenet


True

In [15]:
#5
def sum_of_list(d):

  s=0

  for i in d:
    s=s+i
  return(s)

In [23]:
x=[5,19,13,43,15]
sum_of_list(x)

95

In [31]:
#6
def avg_of_list(d1):

  s=0
  m=len(d1)

  for i in d1:
    s=(s+i)
    k=s/m
  return(k)

In [32]:
x=[5,19,13,43,15]
avg_of_list(x)

19.0

In [33]:
#7
def largest_in_list(d2):
  l=max(d2)
  return(l)

In [35]:
w=[58,98,973,483,915]
largest_in_list(w)

973

In [1]:
#8
def digital_sum(n):
  if n<10:
    return(n)
  else:
    return(digital_sum(n//10+n%10))

In [4]:
digital_sum(78)

6

In [7]:
#9
def power(number,exponent):
  if exponent==0:
    return(1)
  elif exponent<0:
    return(1/power(number,exponent))
  else:
    return(number*power(number,exponent-1))


In [9]:
number=float(input("enter the number-   "))
exponent=float(input("enter the exponent-   "))
print(power(number,exponent))

enter the number-   5
enter the exponent-   3
125.0


In [22]:
#10
g=18
h=9
def GCD(g,h):
  if h==0:
    return(g)
  else:
    return GCD(h,g%h)

print(GCD(g,h))

9


In [25]:
#11
import numpy as np
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
#12
a1= np.arange(1, 10).reshape(3, 3)
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
#13
a2=np.eye(3)
a2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
#14
a3=np.random.randint(1,100,10)
print(a3)
print("mean :",a3.mean())
print("standard deviation :", a3.std())

[97 96 43 99 95 17 95 29 24 69]
mean : 66.4
standard deviation : 32.714522768947745


In [36]:
#15
a1= np.arange(10, 21)
print(a1)
a1[:5]

[10 11 12 13 14 15 16 17 18 19 20]


array([10, 11, 12, 13, 14])

In [47]:
#16
ab=np.arange(16).reshape(4,4)
print(ab)
ab[1:2,0:4]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


array([[4, 5, 6, 7]])

In [51]:
#17
c1=np.arange(5)
c2=np.arange(6,11)
c=c1+c2

print(c1)
print(c2)
print(c)


[0 1 2 3 4]
[ 6  7  8  9 10]
[ 6  8 10 12 14]


In [52]:
#18
ax=np.random.rand(10)
ax

array([0.22112152, 0.26886813, 0.8393399 , 0.73904351, 0.55540358,
       0.7032742 , 0.39663384, 0.44060363, 0.74217571, 0.57922723])

In [55]:
ax[ax<0.5]=0
ax

array([0.        , 0.        , 0.8393399 , 0.73904351, 0.55540358,
       0.7032742 , 0.        , 0.        , 0.74217571, 0.57922723])